name: terraform-ci
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@v2
    with:
      upload_sarif: false
      default_runner_override_label: self-hosted
      runner_label: <your_label_here>
    secrets: inherit
