name: 'Trivy Aqua Security Scan for Docker and ECR Reusable workflow'

on:
  workflow_call:
    inputs:
      docker_file:
        description: Name of the dockerfile
        type: string
        default: ./Dockerfile
        required: false
      docker_tag_name:
        description: Provide the docker tag names
        type: string
        default: ''
        required: false
      docker_tag_version:
         description: Provide the docker tag names
         type: string
         default: 'latest'
         required: false
      docker_build_args:
        description: "Multi-Line list of build args with key value"
        type: string
        required: false
        default: ''
      ecr_image_name:
        description: ECR repo image to scan
        type: string
        required: false
      ecr_tag_version:
        description: ECR repo tag version to scan
        type: string
        required: false
        default: 'latest'
      aws_account_id:
        description: "AWS account ID"
        type: string
        required: false
        default: ''
      aws_account_region:
        description: "AWS account region"
        type: string
        required: false
        default: ''
      aws_iam_role_arn:
       description: "AWS ARN IAM Role"
       type: string
       required: false
       default: ''
      trivy_format:
        description: "Trivy format to log out the scan"
        type: string
        default: 'table'
        required: false
      upload_to_codeql:
        description: "Upload to CodeQL"
        type: boolean
        default: false
        required: false
    secrets:
      OAUTH_TOKEN:
        description: Github Token for accessing other dependency private repo
        required: false

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Variable
      id: set-vars
      run: |
        if [ "${{ inputs.docker_tag_name }}" != "" ]; then
          echo "file_output=trivy-results-docker.sarif" >> "$GITHUB_OUTPUT"
        elif [ "${{ inputs.ecr_image_name }}" != "" ] &&  [ "${{ inputs.aws_account_id }}" != "" ]; then
          echo "file_output=trivy-results-ecr.sarif" >> "$GITHUB_OUTPUT"
        else
          echo "file_output=" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-skip-session-tagging: true
        role-to-assume: ${{ inputs.aws_iam_role_arn }}
        role-session-name: gh-actions
        aws-region: ${{ inputs.aws_account_region }}
      if: ${{ (inputs.docker_tag_name =='') && (inputs.ecr_image_name !='') }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_account_region }}.amazonaws.com/${{ inputs.ecr_image_name}}:${{ inputs.ecr_tag_version }}
        format: ${{ inputs.trivy_format }}
        output: ${{ inputs.upload_to_codeql && steps.set-vars.outputs.file_output || '' }}
      if: ${{ (inputs.docker_tag_name =='') && (inputs.ecr_image_name !='') && (inputs.aws_account_id != '') }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.docker_file }}
        tags:  ${{ inputs.docker_tag_name }}:${{ inputs.docker_tag_version }}
        build-args: |
          GITHUB_OAUTH_TOKEN=${{ secrets.OAUTH_TOKEN }}
          ${{ inputs.docker_build_args }}
        push: false
      if: ${{ inputs.docker_tag_name !='' }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.docker_tag_name }}:${{ inputs.docker_tag_version }}
        format: ${{ inputs.trivy_format }}
        output: ${{ inputs.upload_to_codeql && steps.set-vars.outputs.file_output || '' }}
        ignore-unfixed: false
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'
      if: ${{ inputs.docker_tag_name !='' }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.set-vars.outputs.file_output }}
      if: ${{ inputs.upload_to_codeql }}
