name: Pre-commit auto-update

on:
  # every sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

# Request from Org admin to allow Github Action workflow to make PR under Settings > Actions > General 
permissions:
  actions: read
  checks: read
  contents: write #require this to write to repo
  pull-requests: write #require this to create PR

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: SPHTech-Platform/gha-pre-commit-autoupdate@main
        name: Update pre-commit config automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
