name: GitHub Security Alerts for JIRA

on:
  workflow_call:
    inputs:
      jira_watchers:
        description: JIRA users to add as watchers to tickets. Separate multiple watchers with comma (no spaces).
        type: string
        required: true
      default_runner_override_label:
        description: Change this to "self-hosted" or "ubuntu-latest"
        type: string
        default: "ubuntu-latest"
      runner_label:
        description: Runner label to point to self hosted runners
        type: string
        default: "ubuntu-latest"
      jira_host:
        description: The endpoint for your Jira instance, e.g. https://foo.atlassian.net
        type: string
        default: https://sph.atlassian.net
      jira_user:
        description: The ID of the Jira user which is associated with the 'JiraApiToken' secret, eg 'someuser@sph.com.sg'
        type: string
        default: devopsint@sph.com.sg
      jira_project:
        description: The project key for the Jira project where issues should be created, eg TEST or UAT
        type: string
        default: DD
      jira_issue_type:
        description: Type of issue to create, e.g. Security. Defaults to Bug.
        type: string
        default: Bug
      jira_issue_labels:
        description: Jira labels to add to tickets. Separate multiple labels with comma (no spaces).
        type: string
        default: Drupal-Security
    secrets:
      ORG_GITHUB_TOKEN:
        description: GitHub Organization Service Account Token
        required: true
      JIRA_TOKEN:
        description: JIRA DevOpsInt User Account Token
        required: true

jobs:
  syncSecurityAlerts:
    permissions: read-all
    runs-on:
      - ${{ inputs.default_runner_override_label }}
      - ${{ inputs.runner_label }}
    steps:
      - name: "Sync Security Alerts to JIRA Issues"
        uses: reload/github-security-jira@v1.3.1
        env:
          GH_SECURITY_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ inputs.jira_host }}
          JIRA_USER: ${{ inputs.jira_user }}
          JIRA_PROJECT: ${{ inputs.jira_project }}
          JIRA_ISSUE_TYPE: ${{ inputs.jira_issue_type }}
          JIRA_WATCHERS: ${{ inputs.jira_watchers }}
          JIRA_ISSUE_LABELS: ${{ inputs.jira_issue_labels }}
