name: terraform-ci
on:
  workflow_call:
    inputs:
      upload_sarif:
        description: Upload SARIF results to Github. Available in public repos, or private/internal repos for enterprises with Github Advanced Security.
        type: boolean
        default: true
        required: false
      main_branch:
        description: Name of the main branch
        type: string
        default: main
        required: false
      checkov_skip_check:
        description: Skip a specific check_id. Can be comma separated list.
        type: string
        default: ""
        required: false
      checkov_output_quiet:
        description: Checkov output to display only failures
        type: string
        default: true
        required: false
      checkov_download_external_modules:
        description: Download external modules
        type: boolean
        default: false
        required: false
      enable_submodules:
        description: Flag to enable GitHub submodules.
        type: boolean
        default: false
        required: false
      pre_init_hook:
        description: Shell commands to run before terraform init
        default: ""
        required: false
        type: string
      skip_precommit:
        description: Comma separated list of pre-commit check IDs to skip
        type: string
        default: ""
        required: false
      skip_tflint_warn:
        description: Do not fail for tflint warning
        type: boolean
        default: true
      skip_tflint_warn_for_changed_files:
        description: Enforce tflint warnings for changed files by default
        type: boolean
        default: false
      default_runner_override_label:
        description: Change this to "self-hosted" or "ubuntu-latest"
        type: string
        default: "ubuntu-latest"
      runner_label:
        description: Runner label to point to self hosted runners
        type: string
        default: "ubuntu-latest"
      pre_commit_run_all:
        description: Run pre-commit against all files
        type: boolean
        default: false
    secrets:
      TFE_TOKEN:
        description: Terraform Cloud Token
        required: false

env:
  TF_PLUGIN_CACHE_DIR: "/home/runner/.terraform.d/plugin-cache"
  TF_IN_AUTOMATION: "true"

jobs:
  fmt-validate:
    if: github.ref_name != 'main'
    name: Format and Validate
    runs-on:
      - ${{ inputs.default_runner_override_label }}
      - ${{ inputs.runner_label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: ${{ inputs.enable_submodules }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
      - name: Cache TFLint plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('**/.tflint.hcl') }}

      - name: Setup Node only for self-hosted runners
        uses: actions/setup-node@v3
        if: ${{ inputs.default_runner_override_label == 'self-hosted' }}
        with:
          node-version: 19

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-init Hook
        run: ${{ inputs.pre_init_hook }}

      - name: Precommit Skips
        id: precommit_skips
        run: |
          SKIPS="tflint,terraform_tflint,markdown-link-check,terraform_docs,terraform_tfsec,checkov,terraform_checkov"
          if [ "${branch}" == "${main_branch}" ];then
              SKIPS="${SKIPS},no-commit-to-branch"
          fi
          if [ "${{inputs.skip_precommit}}" != "" ]; then
            SKIPS="${SKIPS},${{inputs.skip_precommit}}"
          fi

          echo "${SKIPS}"
          echo "skips=${SKIPS}" >> "${GITHUB_OUTPUT}"
        env:
          branch: ${{ github.ref_name }}
          main_branch: ${{ inputs.main_branch }}

      - name: precommit run hooks
        id: precommit_run_hooks #Run on all PRs from the same repo, fork repos to run all
        if: inputs.pre_commit_run_all == false
        env:
          SKIP: ${{ steps.precommit_skips.outputs.skips }}
        run: |
          pip install pre-commit
          git fetch origin
          if [ "$GITHUB_EVENT_NAME" == 'pull_request' ]
          then
            if [ ${{ github.event.pull_request.head.repo.full_name }} == ${{ github.repository }} ]
            then
              pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref ${{ github.event.pull_request.head.sha }} --color=always --show-diff-on-failure
            else
              pre-commit run --color=always --show-diff-on-failure --all-files
            fi
          else
            pre-commit run --from-ref origin/${{ github.event.repository.default_branch }} --to-ref "$GITHUB_SHA" --color=always --show-diff-on-failure
          fi

      - name: precommit run tflint hooks
        id: precommit_run_hooks_all
        if: inputs.pre_commit_run_all
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: ${{ steps.precommit_skips.outputs.skips }}
        with:
          extra_args: --color=always --show-diff-on-failure --all-files

      - run: terraform -v

  lint:
    name: Linting
    if: github.ref_name != 'main'
    runs-on:
      - ${{ inputs.default_runner_override_label }}
      - ${{ inputs.runner_label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: ${{ inputs.enable_submodules }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache TFlint
        uses: actions/cache@v3
        with:
          path: /home/runner/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: "v0.44.1"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node only for self-hosted runners
        uses: actions/setup-node@v3
        if: ${{ inputs.default_runner_override_label == 'self-hosted' }}
        with:
          node-version: 19

      - name: Pre-init Hook
        run: ${{ inputs.pre_init_hook }}

      - name: set PY for precommit cache
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"

      - name: Cache Pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Precommit Skips
        id: precommit_skips
        run: |
          SKIPS="shellcheck,terraform_fmt,terraform_providers_lock,markdown-link-check,terraform_docs,terraform_tfsec,checkov,terraform_checkov,terraform_checkov"
          if [ "${branch}" == "${main_branch}" ];then
              SKIPS="${SKIPS},no-commit-to-branch"
          fi
          if [ "${{inputs.skip_precommit}}" != "" ]; then
            SKIPS="${SKIPS},${{inputs.skip_precommit}}"
          fi

          echo "${SKIPS}"
          echo "skips=${SKIPS}" >> "${GITHUB_OUTPUT}"
        env:
          branch: ${{ github.ref_name }}
          main_branch: ${{ inputs.main_branch }}

      - name: precommit run tflint hooks for only changed files
        id: precommit_run_hooks #Run on all PRs from the same repo, fork repos to run all
        if: inputs.pre_commit_run_all == false
        continue-on-error: ${{ inputs.skip_tflint_warn_for_changed_files }}
        env:
          SKIP: ${{ steps.precommit_skips.outputs.skips }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install pre-commit
          git fetch origin
          if [ "$GITHUB_EVENT_NAME" == 'pull_request' ]
          then
            if [ ${{ github.event.pull_request.head.repo.full_name }} == ${{ github.repository }} ]
            then
              pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref ${{ github.event.pull_request.head.sha }} --color=always --show-diff-on-failure
            else
              pre-commit run --color=always --show-diff-on-failure --all-files
            fi
          else
            pre-commit run --from-ref origin/${{ github.event.repository.default_branch }} --to-ref "$GITHUB_SHA" --color=always --show-diff-on-failure
          fi

      - name: precommit run tflint hooks
        id: precommit_run_hooks_all
        if: inputs.pre_commit_run_all
        uses: pre-commit/action@v3.0.0
        continue-on-error: true
        env:
          SKIP: ${{ steps.precommit_skips.outputs.skips }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_args: --color=always --show-diff-on-failure --all-files

      - name: Check status code
        if: steps.precommit_run_hooks.outcome == 'failure'
        run: |
          # SKIP_WARN for skipping all warnings
          skip_warn="${{ inputs.skip_tflint_warn }}"
          if [ "$skip_warn" = true ]; then
            echo "TFLint warnings and errors found and skipped."
          else
            echo "TFLint errors found, expected '0'. Failing... To enable skipping please set 'skip_tflint_warn' to true in workflow file"
            exit 1
          fi

        #steps.tflint.outcome  check for outcome
  security:
    name: Security Checks
    if: github.ref_name != 'main'
    runs-on:
      - ${{ inputs.default_runner_override_label }}
      - ${{ inputs.runner_label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: ${{ inputs.enable_submodules }}

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          flags: -tee
        if: inputs.upload_sarif != true

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@94be32d33f46ce5f2f07200bb5df4f5036b7296c
        with:
          output_format: sarif
          quiet: ${{ inputs.checkov_output_quiet }}
          skip_check: ${{ inputs.checkov_skip_check }}
          download_external_modules: ${{ inputs.checkov_download_external_modules }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
        if: inputs.upload_sarif

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
        if: inputs.upload_sarif
